fix(config): change husky config

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,8 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 echo "Validating your commit message"
 
-# regexes to validate in commit msg
+# regexes to validate in commit message
 
 RED='\033[0;31m'
 BRED='\033[1;31m'
@@ -10,11 +10,11 @@ BRED='\033[1;31m'
 NC='\033[0m'
 
 commit_regex='^(feat|fix|docs|style|refactor|perf|test|chore)(\(([a-zA-Z0-9 \-]+)\))?:'
-error_msg="
+error_message="
 
 ${BRED}Please use semantic commit messages:${NC}
 
-<type>(<scope>): <subject>
+<type>(<scope>): <subject> (P40-<YOUR-JIRA-TICKET_NUMBER>)
 
 ${BRED}types:${NC}
 
@@ -34,26 +34,26 @@ Matches [a-zA-Z0-9 \-]+]
 "
 
 if ! grep -qE "$commit_regex" .git/COMMIT_EDITMSG && ! grep -qE "merge" .git/COMMIT_EDITMSG; then
-    echo -e "$error_msg" >&2
+    echo -e "$error_message" >&2
     exit 1
 fi
 
 
 # regex to validate in commit message
-commit_regex='(#[0-9]+|Bump|merge|noticket)'
-error_msg="
+commit_regex='(P40-[0-9]+|Bump|merge|noticket)'
+error_message="
 
-<type>(<scope>): <subject>
+<type>(<scope>): <subject> (P40-<YOUR-JIRA-TICKET_NUMBER>)
 
 ${BRED}Your commit message is missing one of the following labels in the subject:${NC}
 
-- ${RED}P40-1234${NC}: A Jira ticket number
+- ${RED}(P40-1234)${NC}: A Jira ticket number
 - ${RED}noticket${NC}: Only use this when there is no ticket for this commit
 - ${RED}merge${NC}: When want to commit a merge
 
 "
 
 if ! grep -iqE "$commit_regex" .git/COMMIT_EDITMSG; then
-    echo -e "$error_msg" >&2
+    echo -e "$error_message" >&2
     exit 1
 fi
